export const THIES_QUARTIERS = [
  'Aiglon',
  'Carrière',
  'Cité Lamy',
  'Cité Malick Sy',
  'Darou Salam',
  'Diakhao',
  'Diamaguène',
  'Dixième (10ème)',
  'Escale',
  'Fandène',
  'Grand Thiès',
  'Hersent',
  'Keur Cheikh Ibrahima Fall',
  'Keur Mame El Hadji',
  'Keur Saïb Ndoye',
  'Mbambara',
  'Mbour I',
  'Mbour II',
  'Mbour III',
  'Medina Fall',
  'Mur des plaques',
  'Nguinthe',
  'Parcelles Assainies',
  'Peycouck',
  'Poniène',
  'Randoulène',
  'Route de Dakar',
  'Sampathé',
  'Silmang',
  'Soffene',
  'Som',
  'Takhikao',
  'Thialy',
  'Thiapong',
  'Thionakh'
];
